"""Agregar password a usuario

Revision ID: 2a5820142c5a
Revises: 0bf160a86abc
Create Date: 2026-06-26 10:01:45.446378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5820142c5a'
down_revision = '0bf160a86abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False, server_default='temporal123'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
